# Config file for automatic testing at travis-ci.org

language: python
python:
  - "pypy3"
  - "pypy"
  - "3.8"
  - "3.7"
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"

# Use container-based infrastructure
sudo: false

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -e .[dev]
  - pip install coverage

# command to run tests, e.g. python setup.py test
script:
  - coverage run --source simpleneighbors setup.py test --verbose
  - python -m doctest simpleneighbors/__init__.py

after_success:
- pip install coveralls
- coveralls # send coverage to coveralls.io

after_script:
- coverage report                     # show coverage on cmd line
- flake8 simpleneighbors tests
